In [12]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\ebntl\miniconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\ebntl\miniconda3\Lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ebntl\miniconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\ebntl\miniconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\ebntl\miniconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [13]:
import pandas as pd

In [14]:
# Part 1: Data Loading and Exploration
# Read all CSV files into Pandas DataFrames
df_customers = pd.read_csv("csv_files/wk8-customers.csv")
df_inventory = pd.read_csv("csv_files/wk8-inventory.csv")
df_products = pd.read_csv("csv_files/wk8-products.csv")
df_sales = pd.read_csv("csv_files/wk8-sales.csv")
df_stores = pd.read_csv("csv_files/wk8-stores.csv")

In [15]:
# Display the first few rows of each DataFrame
# First Data Frame (Customers)
df_customers.head()

,customer_id,first_name,last_name,email,phone,address,city,state,zip_code,registration_date
0,1,James,Smith,james.smith@gmail.com,555-123-4567,123 Main St,New York,NY,10001,2021-03-15
1,2,Mary,Johnson,NaN,212.555.6789,456 Park Ave,New York,NY,10022,2020-11-02
2,3,John,Williams,jwilliams@yahoo.com,(555) 987-6543,789 Broadway,Los Angeles,California,90001-1234,2021-05-20
3,4,Patricia,Brown,pbrown@hotmail.com,5551234567,321 Elm St,Chicago,IL,60601,NaN
4,5,Robert,Jones,rjones23@gmail.com,555-987-3456,555 Pine St,Houston,TX,77002,2020-09-12

In [16]:
# Second Data Frame (Inventory)

df_inventory.head()

,inventory_id,store_id,product_id,quantity_in_stock,last_restock_date,reorder_level
0,1,1,1,25,2022-10-15,10.0
1,2,1,5,42,2022-11-02,15.0
2,3,1,10,18,2022-09-30,8.0
3,4,1,15,5,2022-10-20,10.0
4,5,1,20,12,NaN,15.0

In [17]:
# Few Rows from Data Frame (Products)

df_products.head()

,product_id,product_name,category,subcategory,brand,price,cost,weight
0,1,Apple iPhone 13,Electronics,Smartphones,Apple,899.99,649.99,0.45
1,2,Samsung Galaxy S21,electronics,Smartphones,Samsung,799.99,539.99,0.50
2,3,Sony WH-1000XM4,ELECTRONICS,Headphones,Sony,349.99,210.00,0.60
3,4,Dell XPS 13,Electronics,Laptops,Dell,1299.99,899.99,2.80
4,5,Nike Classic Tee,Clothing,Shirts,Nike,24.99,12.50,0.20

In [18]:
# Few Rows from DataFrame (sales)

df_sales.head()

,sale_id,date,store_id,customer_id,product_id,quantity,total,payment_method
0,1,2022-01-15,3.0,12,5,2,49.98,Credit Card
1,2,2022-01-16,1.0,5,10,1,49.99,credit card
2,3,2022-01-18,2.0,8,3,1,349.99,DEBIT CARD
3,4,2022-01-20,4.0,20,7,1,349.99,Cash
4,5,2022-01-22,5.0,3,15,1,1599.99,CC

In [19]:
# Few Rows from dataframe (stores)

df_stores.head()

,store_id,store_name,address,city,state,zip_code,region,size_sqft,opening_date
0,1,City Center,123 Retail Blvd,New York,NY,10001,Northeast,32500.0,2005-05-20
1,2,Mall of Chicago,456 Shopping Ave,Chicago,IL,60611,Midwest,45000.0,2007-08-15
2,3,Los Angeles Plaza,789 Commerce St,Los Angeles,CA,90001,West,55000.0,2004-03-10
3,4,Houston Galleria,321 Main St,Houston,Texas,77002,Southwest,NaN,2008-11-05
4,5,Phoenix Outlet,654 Desert Rd,Phoenix,AZ,85001,Southwest,18500.0,2010-06-30

In [20]:
# 2. Exploratory Analysis

# Obtain summary statistics for numerical columns

df_customers.describe()

       customer_id
count    31.000000
mean     15.838710
std       8.858505
min       1.000000
25%       8.500000
50%      16.000000
75%      23.500000
max      30.000000

In [21]:
df_inventory.describe()

       inventory_id   store_id  product_id  quantity_in_stock  reorder_level
count     75.000000  75.000000   75.000000          75.000000      69.000000
mean      38.000000   8.000000   12.733333          22.640000      12.681159
std       21.794495   4.349588    7.179801          13.923187       3.327659
min        1.000000   1.000000    1.000000           0.000000       8.000000
25%       19.500000   4.000000    6.500000          15.000000      10.000000
50%       38.000000   8.000000   13.000000          25.000000      10.000000
75%       56.500000  12.000000   19.000000          33.500000      15.000000
max       75.000000  15.000000   25.000000          45.000000      20.000000

In [22]:
df_inventory.describe()

       inventory_id   store_id  product_id  quantity_in_stock  reorder_level
count     75.000000  75.000000   75.000000          75.000000      69.000000
mean      38.000000   8.000000   12.733333          22.640000      12.681159
std       21.794495   4.349588    7.179801          13.923187       3.327659
min        1.000000   1.000000    1.000000           0.000000       8.000000
25%       19.500000   4.000000    6.500000          15.000000      10.000000
50%       38.000000   8.000000   13.000000          25.000000      10.000000
75%       56.500000  12.000000   19.000000          33.500000      15.000000
max       75.000000  15.000000   25.000000          45.000000      20.000000

In [23]:
df_products.describe()

       product_id        price         cost     weight
count   30.000000    30.000000    30.000000  28.000000
mean    15.500000   191.724000   203.159000   3.835714
std      8.803408   452.483576   278.924138   5.693236
min      1.000000 -1599.990000     1.800000   0.200000
25%      8.250000    46.990000    28.375000   0.500000
50%     15.500000   134.990000    82.500000   1.150000
75%     22.750000   322.490000   236.250000   3.750000
max     30.000000  1299.990000  1100.000000  25.000000

In [31]:
df_sales.describe()

         sale_id   store_id  customer_id  product_id   quantity        total
count  40.000000  39.000000    40.000000   40.000000  40.000000    40.000000
mean   20.500000   6.487179    14.075000   13.500000   1.625000   352.296500
std    11.690452   4.235637     8.303189    8.857852   0.952392   377.625776
min     1.000000   1.000000     1.000000    1.000000   1.000000    19.980000
25%    10.750000   3.000000     6.750000    5.750000   1.000000    99.737500
50%    20.500000   6.000000    13.500000   11.500000   1.000000   229.985000
75%    30.250000   9.500000    20.250000   21.250000   2.000000   352.487500
max    40.000000  15.000000    29.000000   30.000000   5.000000  1599.990000

In [24]:
df_stores.describe()

        store_id     size_sqft
count  15.000000     13.000000
mean    8.000000  30653.846154
std     4.472136  11342.002717
min     1.000000  16500.000000
25%     4.500000  22000.000000
50%     8.000000  29000.000000
75%    11.500000  35000.000000
max    15.000000  55000.000000

In [25]:
# Check for missing values in all dataframes
# Juypter Notebook can only output one dataframe at one time, comment out which data frame you would like to look at

# df_customers.isna()
# df_inventory.isna()
# df_products.isna()
# df_sales.isna()
# df_stores.isna()

# Display the data types of each column
# Comment out which data frame you want to analyze

# df_customers.dtypes
# df_inventory.dtypes
# df_products.dtypes
# df_sales.dtypes
df_stores.dtypes

store_id          int64
store_name          str
address             str
city                str
state               str
zip_code            str
region              str
size_sqft       float64
opening_date        str
dtype: object

In [26]:
# 3. Basic Information Retrieval

# How many unique products are in the product catalog?
df_products['product_id'].nunique()

# What are the top 5 most expensive products
df_products.nlargest(5, 'price')

# Which store has the largest floor space?
df_stores.nlargest(1, 'size_sqft')

# What is the distribution of customers by state?
df_customers.groupby('state').size().sort_values(ascending=False)

state
TX                4
CA                3
NY                2
AZ                1
CO                1
IL                1
IN                1
California        1
FL                1
MA                1
KY                1
MO                1
MD                1
Maryland          1
NM                1
NV                1
MI                1
North Carolina    1
OH                1
PA                1
Oregon            1
TN                1
Texas             1
WI                1
Washington        1
dtype: int64

In [28]:
# Part 2: Data Cleaning

# 1. Handling Missing Values

# Create copies of original DataFrames for cleaning

df_customers_new = df_customers.copy()
df_inventory_new = df_inventory.copy()
df_products_new = df_products.copy()
df_sales_new = df_sales.copy()
df_stores_new = df_stores.copy()

In [29]:
# Verifying the copies of the dataframes existing

df_customers_new
# df_inventory_new
# df_products_new
# df_sales_new
# df_stores_new

,customer_id,first_name,last_name,email,phone,address,city,state,zip_code,registration_date
0,1,James,Smith,james.smith@gmail.com,555-123-4567,123 Main St,New York,NY,10001,2021-03-15
1,2,Mary,Johnson,NaN,212.555.6789,456 Park Ave,New York,NY,10022,2020-11-02
2,3,John,Williams,jwilliams@yahoo.com,(555) 987-6543,789 Broadway,Los Angeles,California,90001-1234,2021-05-20
3,4,Patricia,Brown,pbrown@hotmail.com,5551234567,321 Elm St,Chicago,IL,60601,NaN
4,5,Robert,Jones,rjones23@gmail.com,555-987-3456,555 Pine St,Houston,TX,77002,2020-09-12
5,6,Jennifer,Miller,jmiller@outlook.com,NaN,898 Cedar Dr,Phoenix,AZ,85001,2021-02-28
6,7,Michael,Davis,mdavis@gmail.com,555.432.7654,742 Maple Ave,Philadelphia,PA,19103,2021-01-17
7,8,Linda,Garcia,lgarcia@yahoo.com,555 876 2345,953 Oak Ln,San Antonio,Texas,78205,2020-10-05
8,9,William,Rodriguez,wrodriguez@hotmail.com,5558889999,159 Washington Blvd,San Diego,CA,92101,2021-06-30
9,10,Elizabeth,Wilson,ewilson@gmail.com,(555) 333-2211,753 Lincoln Rd,Dallas,TX,75201,2020-08-22
10,11,David,Martinez,dmartinez@yahoo.com,555-111-3333,246 Jefferson Ave,San Jose,CA,95113,2021-04-09
11,12,Barbara,Anderson,NaN,555.444.9876,135 Madison St,Austin,TX,NaN,2020-12-27
12,13,Richard,Taylor,rtaylor@outlook.com,5552223333,864 Adams Ct,Jacksonville,FL,32202,2021-07-14
13,14,Susan,Thomas,sthomas45@gmail.com,NaN,579 Monroe Pl,Fort Worth,TX,76102,2020-07-18
14,15,Joseph,Hernandez,jhernandez@yahoo.com,555-777-8888,951 Jackson Dr,Columbus,OH,43215,2021-01-03
15,16,Jessica,Moore,jmoore@hotmail.com,555.666.1234,357 Tyler St,Charlotte,North Carolina,28202,NaN
16,17,Thomas,Martin,tmartin@gmail.com,(555) 444-5678,159 Polk Ave,San Francisco,CA,94102,2020-10-19
17,18,Sarah,Jackson,sjackson@yahoo.com,5557890123,753 Harrison Rd,Indianapolis,IN,46204,2021-03-01
18,19,Charles,Thompson,cthompson@outlook.com,555-321-6547,951 Van Buren St,Seattle,Washington,98101,2020-09-05
19,20,Karen,White,kwhite88@gmail.com,555.789.4561,357 Fillmore Dr,Denver,CO,80202,2021-05-12
20,21,Christopher,Lopez,clopez@yahoo.com,555 456 7890,159 Pierce Ave,Boston,MA,02108,2020-11-30
21,22,Nancy,Lee,nlee@hotmail.com,5559876543,753 Hayes Blvd,Portland,Oregon,97201,2021-02-14
22,23,Daniel,Gonzalez,dgonzalez@gmail.com,(555) 123-7890,951 Grant St,Las Vegas,NV,89101,2020-08-08
23,24,Margaret,Harris,mharris@yahoo.com,555-321-6789,357 Sherman Rd,Detroit,MI,48226,2021-04-25
24,25,Matthew,Clark,mclark@outlook.com,555.654.9870,159 Sheridan Dr,Nashville,TN,37201,NaN
25,26,Betty,Lewis,betty.lewis@gmail.com,5551597532,753 MacArthur Blvd,Baltimore,Maryland,21202,2020-07-01
26,26,Betty,Lewis,blewis23@gmail.com,555 159 7532,753 MacArthur Boulevard,Baltimore,MD,21202,2020-07-01
27,27,Steven,Robinson,srobinson@yahoo.com,555-951-7532,951 Hooker St,Louisville,KY,40202,2021-06-17
28,28,Dorothy,Walker,dwalker@hotmail.com,5553579514,357 Halsted Ave,Milwaukee,WI,53202,2020-09-30
29,29,Anthony,Perez,NaN,555.753.9512,159 Ashland Dr,Albuquerque,NM,87102,2021-01-28
30,30,Lisa,Hall,lhall@gmail.com,(555) 951-7530,753 Morgan St,Kansas City,MO,64101,2020-10-15

In [40]:
# Verifying which columns have missing values

# df_customers_new.isna()
# df_inventory_new.isna()
# df_products_new.isna()
df_sales_new.isna()
# df_stores_new.isna()

# For numerical columns with missing values, replace with column mean

# For categorical columns with missing values, replace with most frequent value

,sale_id,date,store_id,customer_id,product_id,quantity,total,payment_method
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False
10,False,False,True,False,False,False,False,False
11,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False
30,False,True,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,True
33,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False

In [35]:
# for the Customers Table

df_customers_new['registration_date'] = pd.to_datetime(df_customers_new['registration_date'])

df_customers_new['email'] = df_customers_new['email'].fillna(df_customers_new['email'].mode()[0])
df_customers_new['phone'] = df_customers_new['phone'].fillna(df_customers_new['phone'].mode()[0])
df_customers_new['zip_code'] = df_customers_new['zip_code'].fillna(df_customers_new['zip_code'].mode()[0])

df_customers_new['registration_date'] = df_customers_new['registration_date'].fillna(df_customers_new['registration_date'].mean())

In [38]:
# For the Inventory Table

df_inventory_new['last_restock_date'] = pd.to_datetime(df_inventory_new['last_restock_date'])
df_customers_new['last_restock_date'] = df_customers_new['last_restock_date'].fillna(df_customers_new['last_restock_date'].mean())

KeyError: 'last_restock_date'

In [39]:
# For the Products Table

df_products_new['weight'] = df_products_new['weight'].fillna(df_products_new['weight'].mean())

In [ ]:
# For the Sales Table