In [1]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\Josep\miniconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Josep\miniconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Josep\miniconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Josep\miniconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Josep\miniconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
# Part 1: Data Loading and Exploration
# Read all CSV files into Pandas DataFrames
df_customers = pd.read_csv("csv_files/wk8-customers.csv")
df_inventory = pd.read_csv("csv_files/wk8-inventory.csv")
df_products = pd.read_csv("csv_files/wk8-products.csv")
df_sales = pd.read_csv("csv_files/wk8-sales.csv")
df_stores = pd.read_csv("csv_files/wk8-stores.csv")

In [15]:
# Display the first few rows of each DataFrame
# First Data Frame (Customers)
df_customers.head()

,customer_id,first_name,last_name,email,phone,address,city,state,zip_code,registration_date
0,1,James,Smith,james.smith@gmail.com,555-123-4567,123 Main St,New York,NY,10001,2021-03-15
1,2,Mary,Johnson,NaN,212.555.6789,456 Park Ave,New York,NY,10022,2020-11-02
2,3,John,Williams,jwilliams@yahoo.com,(555) 987-6543,789 Broadway,Los Angeles,California,90001-1234,2021-05-20
3,4,Patricia,Brown,pbrown@hotmail.com,5551234567,321 Elm St,Chicago,IL,60601,NaN
4,5,Robert,Jones,rjones23@gmail.com,555-987-3456,555 Pine St,Houston,TX,77002,2020-09-12

In [16]:
# Second Data Frame (Inventory)

df_inventory.head()

,inventory_id,store_id,product_id,quantity_in_stock,last_restock_date,reorder_level
0,1,1,1,25,2022-10-15,10.0
1,2,1,5,42,2022-11-02,15.0
2,3,1,10,18,2022-09-30,8.0
3,4,1,15,5,2022-10-20,10.0
4,5,1,20,12,NaN,15.0

In [17]:
# Few Rows from Data Frame (Products)

df_products.head()

,product_id,product_name,category,subcategory,brand,price,cost,weight
0,1,Apple iPhone 13,Electronics,Smartphones,Apple,899.99,649.99,0.45
1,2,Samsung Galaxy S21,electronics,Smartphones,Samsung,799.99,539.99,0.50
2,3,Sony WH-1000XM4,ELECTRONICS,Headphones,Sony,349.99,210.00,0.60
3,4,Dell XPS 13,Electronics,Laptops,Dell,1299.99,899.99,2.80
4,5,Nike Classic Tee,Clothing,Shirts,Nike,24.99,12.50,0.20

In [18]:
# Few Rows from DataFrame (sales)

df_sales.head()

,sale_id,date,store_id,customer_id,product_id,quantity,total,payment_method
0,1,2022-01-15,3.0,12,5,2,49.98,Credit Card
1,2,2022-01-16,1.0,5,10,1,49.99,credit card
2,3,2022-01-18,2.0,8,3,1,349.99,DEBIT CARD
3,4,2022-01-20,4.0,20,7,1,349.99,Cash
4,5,2022-01-22,5.0,3,15,1,1599.99,CC

In [19]:
# Few Rows from dataframe (stores)

df_stores.head()

,store_id,store_name,address,city,state,zip_code,region,size_sqft,opening_date
0,1,City Center,123 Retail Blvd,New York,NY,10001,Northeast,32500.0,2005-05-20
1,2,Mall of Chicago,456 Shopping Ave,Chicago,IL,60611,Midwest,45000.0,2007-08-15
2,3,Los Angeles Plaza,789 Commerce St,Los Angeles,CA,90001,West,55000.0,2004-03-10
3,4,Houston Galleria,321 Main St,Houston,Texas,77002,Southwest,NaN,2008-11-05
4,5,Phoenix Outlet,654 Desert Rd,Phoenix,AZ,85001,Southwest,18500.0,2010-06-30

In [20]:
# 2. Exploratory Analysis

# Obtain summary statistics for numerical columns

df_customers.describe()

       customer_id
count    31.000000
mean     15.838710
std       8.858505
min       1.000000
25%       8.500000
50%      16.000000
75%      23.500000
max      30.000000

In [21]:
df_inventory.describe()

       inventory_id   store_id  product_id  quantity_in_stock  reorder_level
count     75.000000  75.000000   75.000000          75.000000      69.000000
mean      38.000000   8.000000   12.733333          22.640000      12.681159
std       21.794495   4.349588    7.179801          13.923187       3.327659
min        1.000000   1.000000    1.000000           0.000000       8.000000
25%       19.500000   4.000000    6.500000          15.000000      10.000000
50%       38.000000   8.000000   13.000000          25.000000      10.000000
75%       56.500000  12.000000   19.000000          33.500000      15.000000
max       75.000000  15.000000   25.000000          45.000000      20.000000

In [22]:
df_inventory.describe()

       inventory_id   store_id  product_id  quantity_in_stock  reorder_level
count     75.000000  75.000000   75.000000          75.000000      69.000000
mean      38.000000   8.000000   12.733333          22.640000      12.681159
std       21.794495   4.349588    7.179801          13.923187       3.327659
min        1.000000   1.000000    1.000000           0.000000       8.000000
25%       19.500000   4.000000    6.500000          15.000000      10.000000
50%       38.000000   8.000000   13.000000          25.000000      10.000000
75%       56.500000  12.000000   19.000000          33.500000      15.000000
max       75.000000  15.000000   25.000000          45.000000      20.000000

In [23]:
df_products.describe()

       product_id        price         cost     weight
count   30.000000    30.000000    30.000000  28.000000
mean    15.500000   191.724000   203.159000   3.835714
std      8.803408   452.483576   278.924138   5.693236
min      1.000000 -1599.990000     1.800000   0.200000
25%      8.250000    46.990000    28.375000   0.500000
50%     15.500000   134.990000    82.500000   1.150000
75%     22.750000   322.490000   236.250000   3.750000
max     30.000000  1299.990000  1100.000000  25.000000

In [31]:
df_sales.describe()

         sale_id   store_id  customer_id  product_id   quantity        total
count  40.000000  39.000000    40.000000   40.000000  40.000000    40.000000
mean   20.500000   6.487179    14.075000   13.500000   1.625000   352.296500
std    11.690452   4.235637     8.303189    8.857852   0.952392   377.625776
min     1.000000   1.000000     1.000000    1.000000   1.000000    19.980000
25%    10.750000   3.000000     6.750000    5.750000   1.000000    99.737500
50%    20.500000   6.000000    13.500000   11.500000   1.000000   229.985000
75%    30.250000   9.500000    20.250000   21.250000   2.000000   352.487500
max    40.000000  15.000000    29.000000   30.000000   5.000000  1599.990000

In [24]:
df_stores.describe()

        store_id     size_sqft
count  15.000000     13.000000
mean    8.000000  30653.846154
std     4.472136  11342.002717
min     1.000000  16500.000000
25%     4.500000  22000.000000
50%     8.000000  29000.000000
75%    11.500000  35000.000000
max    15.000000  55000.000000

In [25]:
# Check for missing values in all dataframes
# Juypter Notebook can only output one dataframe at one time, comment out which data frame you would like to look at

# df_customers.isna()
# df_inventory.isna()
# df_products.isna()
# df_sales.isna()
# df_stores.isna()

# Display the data types of each column
# Comment out which data frame you want to analyze

# df_customers.dtypes
# df_inventory.dtypes
# df_products.dtypes
# df_sales.dtypes
# df_stores.dtypes

store_id          int64
store_name          str
address             str
city                str
state               str
zip_code            str
region              str
size_sqft       float64
opening_date        str
dtype: object

In [26]:
# 3. Basic Information Retrieval

# How many unique products are in the product catalog?
df_products['product_id'].nunique()

# What are the top 5 most expensive products
df_products.nlargest(5, 'price')

# Which store has the largest floor space?
df_stores.nlargest(1, 'size_sqft')

# What is the distribution of customers by state?
df_customers.groupby('state').size().sort_values(ascending=False)

state
TX                4
CA                3
NY                2
AZ                1
CO                1
IL                1
IN                1
California        1
FL                1
MA                1
KY                1
MO                1
MD                1
Maryland          1
NM                1
NV                1
MI                1
North Carolina    1
OH                1
PA                1
Oregon            1
TN                1
Texas             1
WI                1
Washington        1
dtype: int64

In [23]:
# Part 2: Data Cleaning

# 1. Handling Missing Values

# Create copies of original DataFrames for cleaning

df_customers_new = df_customers.copy()
df_inventory_new = df_inventory.copy()
df_products_new = df_products.copy()
df_sales_new = df_sales.copy()
df_stores_new = df_stores.copy()

In [19]:
# Verifying the copies of the dataframes existing

df_customers_new
df_inventory_new
df_products_new
df_sales_new
df_stores_new

,store_id,store_name,address,city,state,zip_code,region,size_sqft,opening_date
0,1,City Center,123 Retail Blvd,New York,NY,10001,Northeast,32500.0,2005-05-20
1,2,Mall of Chicago,456 Shopping Ave,Chicago,IL,60611,Midwest,45000.0,2007-08-15
2,3,Los Angeles Plaza,789 Commerce St,Los Angeles,CA,90001,West,55000.0,2004-03-10
3,4,Houston Galleria,321 Main St,Houston,Texas,77002,Southwest,NaN,2008-11-05
4,5,Phoenix Outlet,654 Desert Rd,Phoenix,AZ,85001,Southwest,18500.0,2010-06-30
5,6,Philadelphia Center,987 Market St,Philadelphia,PA,19103,Northeast,22000.0,2009-09-12
6,7,San Antonio Mall,741 River Walk,San Antonio,TX,78205,Southwest,35000.0,2012-04-22
7,8,San Diego Plaza,852 Pacific Hwy,San Diego,CA,92101,West,27500.0,2006-07-18
8,9,Dallas Galleria,963 Lone Star Blvd,Dallas,TX,75201-5555,Southwest,42000.0,NaN
9,10,Boston Outlet,159 Freedom Rd,Boston,Massachusetts,02108,Northeast,16500.0,2014-10-09
10,11,Seattle City Center,753 Rainy St,Seattle,WA,98101,West,29000.0,2011-02-14
11,12,Denver Mountain Mall,951 Mile High Dr,Denver,CO,80202,West,31500.0,2015-08-27
12,13,Miami Beach Plaza,357 Ocean Dr,Miami,FL,33139,Southeast,24000.0,2016-12-03
13,14,Minneapolis Galleria,852 Lake St,Minneapolis,MN,55401,Midwest,NaN,2013-05-11
14,15,Atlanta Outlet,456 Peachtree St,Atlanta,Georgia,30303,Southeast,20000.0,2018-09-25

In [17]:
# Verifying which columns have missing values

# df_customers_new.isna()
# df_inventory_new.isna()
# df_products_new.isna()
# df_sales_new.isna()
# df_stores_new.isna()

# For numerical columns with missing values, replace with column mean

# For categorical columns with missing values, replace with most frequent value

,sale_id,date,store_id,customer_id,product_id,quantity,total,payment_method
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False
10,False,False,True,False,False,False,False,False
11,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False
30,False,True,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,True
33,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False

In [85]:
# for the Customers Table

'''
Logic:
using the .to_datetime function to change the date values to datetime for analysis

recognizing that email, phone, and zip_code are categorical, using the mode values. With Python indexing at 0, Choosing specifically
the pull only the first one, or [0]
'''

df_customers_new['registration_date'] = pd.to_datetime(df_customers_new['registration_date'])

df_customers_new['email'] = df_customers_new['email'].fillna(df_customers_new['email'].mode()[0])
df_customers_new['phone'] = df_customers_new['phone'].fillna(df_customers_new['phone'].mode()[0])
df_customers_new['zip_code'] = df_customers_new['zip_code'].fillna(df_customers_new['zip_code'].mode()[0])
df_customers_new['registration_date'] = df_customers_new['registration_date'].fillna(df_customers_new['registration_date'].median())

In [86]:
# For the Inventory Table

'''
logic:
using .to_datetime to change date values as previously mentioned
'''

df_inventory_new['last_restock_date'] = pd.to_datetime(df_inventory_new['last_restock_date'])

df_inventory_new['last_restock_date'] = df_inventory_new['last_restock_date'].fillna(df_inventory_new['last_restock_date'].median())
df_inventory_new['reorder_level'] = df_inventory_new['reorder_level'].fillna(df_inventory_new['reorder_level'].mean())

In [87]:
# For the Products Table

'''
logic:

Using .mean as "weight" is a numerical value
'''

df_products_new['weight'] = df_products_new['weight'].fillna(df_products_new['weight'].mean())

In [88]:
# For the Sales Table

'''
logics:

Using .to_datetime for help later

'''

df_sales_new['date'] = pd.to_datetime(df_sales_new['date'])

df_sales_new['date'] = df_sales_new['date'].fillna(df_sales_new['date'].median())
df_sales_new['store_id'] = df_sales_new['store_id'].fillna(df_sales_new['store_id'].mode()[0])
df_sales_new['payment_method'] = df_sales_new['payment_method'].fillna(df_sales_new['payment_method'].mode()[0])

In [89]:
# For the Stores Table, size_sqft	opening_date

'''

logics:

Using .to_datetime for analysis purposes later
Outside of, recognizing that dates and squarefeets are numerical values that can be manipulated, so using .mean for those

'''

df_stores_new['opening_date'] = pd.to_datetime(df_stores_new['opening_date'])

df_stores_new['opening_date'] = df_stores_new['opening_date'].fillna(df_stores_new['opening_date'].median())
df_stores_new['size_sqft'] = df_stores_new['size_sqft'].fillna(df_stores_new['size_sqft'].mean())

In [90]:
## Verification of no more missing values

#df_customers_new.isna().sum()
df_inventory_new.isna().sum()
#df_products_new.isna().sum()
#df_sales_new.isna().sum()
#df_stores_new.isna().sum()

inventory_id         0
store_id             0
product_id           0
quantity_in_stock    0
last_restock_date    0
reorder_level        0
dtype: int64

## Workshop Questions

- 1. What are the key advantages of using Pandas for data cleaning compared to other methods?
- 2. How would your approach to handling missing values differ if the missing data was not random but had a pattern or meaning?
- 3. What types of data quality issues might not be immediately visible through simple DataFrame inspection methods?
- 4. How would you document your data cleaning process to ensure reproducibility?
- 5. In what scenarios might it be better to remove rows with missing values rather than imputing them?

### Answer 1

*What are the key advantages of using Pandas for data cleaning compared to other methods?*

The key advantages for using Pandas for data cleaning in comparison to other methods is the ease of use in adjusting the values. Being able to combine and chain commands such as isna() with any() lets you figure out easily if any columns have any missing values. After, you can chain isna() with sum() to figure out how much missing values exist. Further, with pandas and jupyter lab, you can go and re-run each cell as numerous amounts of times as possible to verify data results. You can use streamlit as well for this, but that's outside of the realm of this question.

### Answer 2

*How would your approach to handling missing values differ if the missing data was not random but had a pattern or meaning?*

The approach to handling missing values would differ if the missing data was pattern/meaning in how I would go about fixing it. If it was random, then I would use the very same instructions used in this workshop, but if there's a pattern to it, then I would take extra time to investigate the lead from the pattern or meaning, and then approach fixing it from the info I got from that lead. For example, if there's missing values in the last_restock_date with a specific store_id, then as a business analysis, I would wonder why, for example, there are numerous missing values for last_restock_date.

### Answer 3

*What types of data quality issues might not be immediately visible through simple DataFrame inspection methods?*

Certain data quality issues that might not be visible is how numeric values might become strings, which will cause issues with having to convert them to numerical datatypes for observations. Other issues are akin to values that a human would consider null, but python wouldn't. For example, the values of *"NA", "N/A", "Null"*, etc will be considered as non-nulls to the interpreter when they would be considered as null values to the average human. One other data quality issue that will arise from using only the inspection methods is logic issues that won't be caught by the computer, which is an extension of logic errors in other programming languages. The interpreter and compilers won't catch these, it's up to the human to catch them. Some of these issues are dates being formatted differently as well as trailing spaces which would make **John Doe** different from **John Doe ** (with a trailing space) in the eyes of a programming language.

### Answer 4

*How would you document your data cleaning process to ensure reproducibility?*

For Data Cleaning Documentation, it would entirely depend on what I would use for the data cleaning. When it comes **to Excel**, I would use a combination of comments as well as merging sections of cells to documentate the process. For **SQL and Python**, I would use the respective language's comment systems at the very least. For Python in particular, if I am using a front-end package like Streamlit, I will deliberately complement the web page with containers of information for documentation. I can also use Markdown in Jupyter lab, such as how I'm using it in this workshop to answer the questions.

### Answer 5

*In what scenarios might it be better to remove rows with missing values rather than imputing them?*

The situations that will be useful to remove rows with missing values rather than imputing with various values will be the situations where you'll need upmost precision with the datasets. Healthcare companies will not tolerate guesses when it comes to various aspects such as medicine dosages. Another situation that will be useful to remove rows with missing values rather than imputing values is if that values missing are analytically insignificant. An email value associated with patrons won't be considered **analytically significant** for analysis as the analysis will focus more on the sales of books and the relations between the patrons and books being sold or rented out.